name: Simple Deploy

on:
  push:
    branches:
      - main
      - staging
      - develop

env:
  TF_VERSION: '1.5.0'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Determine environment
      id: env
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "environment=prod" >> $GITHUB_OUTPUT
          echo "image_tag=stable" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
          echo "environment=staging" >> $GITHUB_OUTPUT
          echo "image_tag=staging" >> $GITHUB_OUTPUT
        else
          echo "environment=dev" >> $GITHUB_OUTPUT
          echo "image_tag=latest" >> $GITHUB_OUTPUT
        fi
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/910196537412/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'github-actions-sa@lucitra-ai.iam.gserviceaccount.com'
    
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Build and Push Docker Image
      run: |
        # Build locally and push to Artifact Registry
        docker build -t us-central1-docker.pkg.dev/lucitra-ai/webhook-server/lucitra-webhook-server:${{ github.sha }} .
        docker build -t us-central1-docker.pkg.dev/lucitra-ai/webhook-server/lucitra-webhook-server:${{ steps.env.outputs.image_tag }} .
        
        # Configure docker auth
        gcloud auth configure-docker us-central1-docker.pkg.dev
        
        # Push images
        docker push us-central1-docker.pkg.dev/lucitra-ai/webhook-server/lucitra-webhook-server:${{ github.sha }}
        docker push us-central1-docker.pkg.dev/lucitra-ai/webhook-server/lucitra-webhook-server:${{ steps.env.outputs.image_tag }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy lucitra-webhook-server-${{ steps.env.outputs.environment }} \
          --image us-central1-docker.pkg.dev/lucitra-ai/webhook-server/lucitra-webhook-server:${{ github.sha }} \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --set-env-vars NODE_ENV=${{ steps.env.outputs.environment }},HUBSPOT_WEBHOOK_SECRET=${{ secrets.HUBSPOT_WEBHOOK_SECRET }}
    
    - name: Get Service URL
      run: |
        echo "🚀 Deployed to:"
        gcloud run services describe lucitra-webhook-server-${{ steps.env.outputs.environment }} \
          --region us-central1 \
          --format 'value(status.url)'